let items = {
    pickaxe: {frame:162},
    shovel : {frame:163},
    wood : {frame:272},
    stone : {frame:273},
    berries : {frame:228},
    meat : {frame:241},
    fur : {frame: 280},
    health_potion: {frame: 144},
    wand_fire: {frame: 105},
    battleaxe: {frame:92},
    mushroom: {frame:236},
    handaxe: {frame:91},
    plainsword: {frame:81},
    greensword: {frame:82},
    woodaxe: {frame:161},
    everleaf: {frame:189},
    entleaf: {frame:191},
  };
  export default items;